apiVersion: v1
kind: Service
metadata:
  name: veetee-service
  namespace: veetee
  labels:
    app: veetee
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP